### ISSUE TITLE
Legend or descriptions for categories

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/prospatheia#19]

**Comment by hlapp** [comment]
- R&D: _self-directed work, work initiated in Informatics, and professional development_
- admin: _staff meetings, emails, administrative work, and HR-required training_
- collaborative projects: _collaborative projects (even if they originated from tickets); typically includes intellectual contribution of some kind, in contrast to troubleshooting or fulfilling service requests_
- infrastructure projects: _physical or virtual work that affects multiple users (in contrast to an individual requestor on a ticket)_
- ticket-based work: _work responding to requests or reports sent to IT, in contrast to initiated in IT; includes such work even if not recorded in a ticket; should not include collaborative or infrastructure projects (which sometimes start as a ticket)_

**Comment by hlapp** [comment]
@dleehr: could these be tool tips or roll-overs?

**Comment by dleehr** [comment]
Yes. I think nvd3 already does that, should be pretty easy: http://nvd3.org/examples/pie.html
