### ISSUE TITLE
Categories for Proteomics core

### ISSUE THREAD

**Issue by hlapp** [Duke-GCB/prospatheia#39]
- Administrative
- Billable
- Education
- Lab Maintenance
- Project Development
- Service Development

**Comment by dleehr** [comment]
Fixed in #41

**Comment by dleehr** [comment]
Updated details
1. Admin  
   - Staff/Lab/Department/Center meetings
   - Ordering, general email, time reporting
   - SOP development, safety courses
2. Billable
   - Effort on grants and projects
   - Project specific technical troubleshooting
   - Email/TC/meetings on active projects
3. Education
   - Presentations for outreach at Duke
   - Training and professional development
   - Conferences (preparation and attendance)
   - Service (manuscript reviews, society participation)
4. Lab Maint.
   - General lab/equipment maintenance and repair
5. Project Dev.
   - Consultations/correspondence for potential projects
   - Proposal preparation, letters of support
6. Service Dev.
   - Non-funded research
   - Development of new services
   - General protocol testing and optimization
7. Personal Time Off
   - Vacation
   - Sick days
