### ISSUE TITLE
Categories for Microarray Core

### ISSUE THREAD

**Issue by hlapp** [Duke-GCB/prospatheia#42]
1. Laboratory and computer maintenance 
2. Laboratory and computer operations 
3. Effort on grants 
4. Education, training and outreach
5. Consultation
6. Professional services

**Comment by dleehr** [comment]
TODO:
- [x] GitHub IDs of staff added to app/groups.js
- [x] staff granted access to data repo
- [x] summary text for categories (optional)

**Comment by dleehr** [comment]
@hlapp can you grant the users access to the data repo?

**Comment by hlapp** [comment]
> @hlapp can you grant the users access to the data repo?

Done.

**Comment by dleehr** [comment]
Summary text added in #50, all tasks complete
