### ISSUE TITLE
Categories for Sequencing Core

### ISSUE THREAD

**Issue by hlapp** [Duke-GCB/prospatheia#46]
The Sequencing core will use the same categories as Microarray, see #42. 

@ofedrigo, please comment here if any differences do arise, and please also add here if for any of the categories you would like explanatory text to show up on hover over the respective slice of the pie chart.

**Comment by dleehr** [comment]
Updated categories - sequencing core will not use same categories:
1. Lab maintenance & Administration
   - Administration (ordering,sales rep etc.); 
   - Lab maintenance (inventory, SOP, safety, washes etc…); 
   - Computer maintenance.
2. Staff administration
   - Administration (reporting, time tracking etc…); 
   - Staff Management; 
   - Staff meeting (lab meeting, center meeting etc…).
3. Projects
   - Lab efforts associated with projects (sample handling, QC, lib preps, sequencing, data distribution etc..). 
   - Project troubleshooting; 
   - Client communication during a project; 
   - Primary and secondary bioinformatics analyses associated to a project; 
   - Programming efforts devoted to a project.
4. Education & Outreach
   - Outreach (performing presentations, going to vendor show etc…); 
   - Education (offering lectures, workshops, 1:1 training, facility tours, etc. 
   - Receiving training and professional development; 
   - Going to conferences; 
   - Continuing education (reading literature, watching webcasts, etc…).
5. Consultation
   - Meeting/corresponding with clients before starting a project; 
   - Preaward support.
6. Development, Research, and Services
   - Product development (Protocol testing, optimization, and customization); 
   - Non-funded research; 
   - Services (proposal and manuscript review not associated with clients, society participation, committees etc…).
7. Effort on grants
   - Efforts devoted to a funded project with salary support.

**Comment by ofedrigo** [comment]
do the percentages have to be integer?

Thanks,

Olivier

From:  Dan Leehr
Reply-To:  Duke-GCB/prospatheia
Date:  Monday, December 7, 2015 at 1:27 PM
To:  Duke-GCB/prospatheia
Cc:  Olivier Fedrigo
Subject:  Re: [prospatheia] Categories for Sequencing Core (#46)

Updated categories:
Lab maintenance & Administration 
Administration (ordering,sales rep etc.); 
Lab maintenance (inventory, SOP, safety, washes etc…); 
Computer maintenance.
Staff administration 
Administration (reporting, time tracking etc…); 
Staff Management; 
Staff meeting (lab meeting, center meeting etc…).
Projects 
Lab efforts associated with projects (sample handling, QC, lib preps, sequencing, data distribution etc..). 
Project troubleshooting; 
Client communication during a project; 
Primary and secondary bioinformatics analyses associated to a project; 
Programming efforts devoted to a project.
Education & Outreach 
Outreach (performing presentations, going to vendor show etc…); 
Education (offering lectures, workshops, 1:1 training, facility tours, etc. 
Receiving training and professional development; 
Going to conferences; 
Continuing education (reading literature, watching webcasts, etc…).
Consultation 
Meeting/corresponding with clients before starting a project; 
Preaward support.
Development, Research, and Services 
Product development (Protocol testing, optimization, and customization); 
Non-funded research; 
Services (proposal and manuscript review not associated with clients, society participation, committees etc…).
Effort on grants 
Efforts devoted to a funded project with salary support.

**Comment by dleehr** [comment]
For user-entered data in Prospatheia, yes. The app will round to the nearest integer and normalize to 100%. It was optimized for quick entry, with some mobile usage in mind (hence the buttons that change in increments of 5%).

If you would like to upload past data in CSV format, non-integer values are fine there and won’t be rounded or truncated.

On Dec 7, 2015, at 2:47 PM, Olivier Fedrigo <notifications@github.com<mailto:notifications@github.com>> wrote:

do the percentages have to be integer?

Thanks,

Olivier

From: Dan Leehr
Reply-To: Duke-GCB/prospatheia
Date: Monday, December 7, 2015 at 1:27 PM
To: Duke-GCB/prospatheia
Cc: Olivier Fedrigo
Subject: Re: [prospatheia] Categories for Sequencing Core (#46)

Updated categories:
Lab maintenance & Administration
Administration (ordering,sales rep etc.);
Lab maintenance (inventory, SOP, safety, washes etc…);
Computer maintenance.
Staff administration
Administration (reporting, time tracking etc…);
Staff Management;
Staff meeting (lab meeting, center meeting etc…).
Projects
Lab efforts associated with projects (sample handling, QC, lib preps, sequencing, data distribution etc..).
Project troubleshooting;
Client communication during a project;
Primary and secondary bioinformatics analyses associated to a project;
Programming efforts devoted to a project.
Education & Outreach
Outreach (performing presentations, going to vendor show etc…);
Education (offering lectures, workshops, 1:1 training, facility tours, etc.
Receiving training and professional development;
Going to conferences;
Continuing education (reading literature, watching webcasts, etc…).
Consultation
Meeting/corresponding with clients before starting a project;
Preaward support.
Development, Research, and Services
Product development (Protocol testing, optimization, and customization);
Non-funded research;
Services (proposal and manuscript review not associated with clients, society participation, committees etc…).
Effort on grants
Efforts devoted to a funded project with salary support.

**Comment by dleehr** [comment]
Categories were added in #49. Import of prior data is outside the scope of this issue, so I'm closing this one.
