### ISSUE TITLE
App should warn if duplicate records are about to be added

### ISSUE THREAD

**Issue by hlapp** [Duke-GCB/prospatheia#54]
The app currently allows the same record to be added (through the simple click of a button) multiple times, without any warning, confirmation, or other visual cue. I believe the Save action does not check for or warns about duplicated records either.

Since there is practically no good reason to add (or save) the exact same record more than once, there should be at least some kind of dialog asking for confirmation. Though it could also be rejected outright (until we have a case that justifies adding duplicate records - right now I don't see one).

**Comment by dleehr** [comment]
Fixed in #57
